python pacman.py -n 5 -l .DS_S -p MinimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l .DS_S -p AlphaBetaAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l .DS_S -p ExpectimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l trappedClassic -p MinimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l trappedClassic -p AlphaBetaAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l trappedClassic -p ExpectimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l contestClassic -p MinimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l contestClassic -p AlphaBetaAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l contestClassic -p ExpectimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l powerClassic -p MinimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l powerClassic -p AlphaBetaAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l powerClassic -p ExpectimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l capsuleClassic -p MinimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l capsuleClassic -p AlphaBetaAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l capsuleClassic -p ExpectimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l mediumClassic -p MinimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l mediumClassic -p AlphaBetaAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l mediumClassic -p ExpectimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l smallClassic -p MinimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l smallClassic -p AlphaBetaAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l smallClassic -p ExpectimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l minimaxClassic -p MinimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l minimaxClassic -p AlphaBetaAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l minimaxClassic -p ExpectimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l testClassic -p MinimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l testClassic -p AlphaBetaAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l testClassic -p ExpectimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l trickyClassic -p MinimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l trickyClassic -p AlphaBetaAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l trickyClassic -p ExpectimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l originalClassic -p MinimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l originalClassic -p AlphaBetaAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l originalClassic -p ExpectimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l openClassic -p MinimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l openClassic -p AlphaBetaAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l openClassic -p ExpectimaxAgent -a depth=2,evalFn=finalEvaluationFunction -q
python pacman.py -n 5 -l .DS_S -p MinimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l .DS_S -p AlphaBetaAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l .DS_S -p ExpectimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l trappedClassic -p MinimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l trappedClassic -p AlphaBetaAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l trappedClassic -p ExpectimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l contestClassic -p MinimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l contestClassic -p AlphaBetaAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l contestClassic -p ExpectimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l powerClassic -p MinimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l powerClassic -p AlphaBetaAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l powerClassic -p ExpectimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l capsuleClassic -p MinimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l capsuleClassic -p AlphaBetaAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l capsuleClassic -p ExpectimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l mediumClassic -p MinimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l mediumClassic -p AlphaBetaAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l mediumClassic -p ExpectimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l smallClassic -p MinimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l smallClassic -p AlphaBetaAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l smallClassic -p ExpectimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l minimaxClassic -p MinimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l minimaxClassic -p AlphaBetaAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l minimaxClassic -p ExpectimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l testClassic -p MinimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l testClassic -p AlphaBetaAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l testClassic -p ExpectimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l trickyClassic -p MinimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l trickyClassic -p AlphaBetaAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l trickyClassic -p ExpectimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l originalClassic -p MinimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l originalClassic -p AlphaBetaAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l originalClassic -p ExpectimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l openClassic -p MinimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l openClassic -p AlphaBetaAgent -a depth=2,evalFn=oldEvaluationFunction -q
python pacman.py -n 5 -l openClassic -p ExpectimaxAgent -a depth=2,evalFn=oldEvaluationFunction -q
